### ISSUE TITLE
Feature: User can view a list of all Agents

### ISSUE THREAD

**Issue by NateNobleza** [NateNobleza/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of all playable agents in the game
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to learn about agents and the roles and abilities that the agents have. They will also be able to filter agents according to role and playstyle.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![screenshot of wire frame](https://github.com/NateNobleza/front-end-project/assets/154506686/09096931-7b42-407e-aa1f-27b6dae22882)
![screen shot of wire frame 2](https://github.com/NateNobleza/front-end-project/assets/154506686/582f1aa6-698e-4fe5-978a-4af892f809cb)
![mobile wireframe 1](https://github.com/NateNobleza/front-end-project/assets/154506686/d7660413-ccf7-4931-bf9a-a11842eb72ee)
![mobile wireframe 2](https://github.com/NateNobleza/front-end-project/assets/154506686/ba03845b-be83-4295-b784-837bbe25e77a)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] add event listener for button click for search button
- [ ] users should be able to view all entries when clicking a button
- [ ] Use form control for drop down menu 
- [ ] Use form control to input a search box
- [ ] Use flexbox to update the viewpoint of both desktop and mobile
- [ ] check that the search entries look good both on desktop and mobile
- [ ] use fetch method to interact with API targeting the appropriate info
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
